### ISSUE TITLE
Unavailable when the WAN internet is down or slow

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-vicreo-hotkey#85]
**Describe the bug**
It has repeatedly happened to me that when I start the computer, the application reports that I do not have a license, which is not true. He had to click on LICENSE INFO and then give UPDATE. Then everything worked correctly.
The error is most likely caused by the fact that the application expects available internet immediately after launch. But my computer connects to the internet later or doesn't have internet available right away.
The quality of the Internet connection should not be a limit for the operation of the application.

**Version**
8.2.4 Basic

**To Reproduce**
Steps to reproduce the behaviour:

1. Disconnect internet
2. Run App

**Expected behaviour**
Fully functional because I paid for the license.

**System (please complete the following information):**

- Companion 3.3.1 (3.3.1+7001-stable-ee7c3daa)
- Win11
- Chrome last

**Additional context**

![image](https://github.com/user-attachments/assets/fe6de6fb-70d9-4b81-9959-3d4359a2a808)
![image](https://github.com/user-attachments/assets/a81d4840-8c6e-4f19-886f-ecfe4d88642c)

**Comment by jryan324** [comment]
I also have this problem... Its a real issue whenever production machines arent connected to the internet regularly. The only solution is to leave the machine on which is not ideal.

**Comment by jryan324** [comment]
Thanks for the reply Jeffrey!

Would you have a rough ETA on when it would be released?

Cheers!

**Comment by JeffreyDavidsz** [comment]
I'm hoping within the next two weeks. I need to test before release on different platforms also.

**Comment by JeffreyDavidsz** [comment]
To check, the license key is there when you go to the license page right? Only not activated?

**Comment by jryan324** [comment]
Correct, its already filled out with the key but you can't activate without Internet access.
________________________________

**Comment by JeffreyDavidsz** [comment]
This issue is fixed in the 9.X.X versions and above

**Comment by jryan324** [comment]
Just in time for Christmas!! Thanks!

**Comment by Suenee** [comment]
> This issue is fixed in the 9.X.X versions and above

I'm sorry, but the error still appears even after updating Vicreo to 9.2.0. See images!

![Image](https://github.com/user-attachments/assets/9b61586e-8260-4425-a49d-087cd655e4cd)

![Image](https://github.com/user-attachments/assets/3f57d079-34bc-402e-9bb9-6cb46a47db3c)
